### ISSUE TITLE
Problem with Virtual Machine

### ISSUE THREAD

**Issue by juancleon** [csudh/toro-net#10]
Hello,
        I am having a problem with the virtualbox software. It appears it is not loading the ubuntu image correctly. It appears to have entered an 'unknown' state. I copied and pasted the output from the command prompt below. Any help anyone can provide would be greatly appreciated.

Juan

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/xenial64' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'ubuntu/xenial64'
    default: URL: https://vagrantcloud.com/ubuntu/xenial64
==> default: Adding box 'ubuntu/xenial64' (v20170922.0.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/ubuntu/boxes/xenial64/versions/20170922.0.0/providers/virtualbox.box
    default: Progress: 100% (Rate: 1719k/s, Estimated time remaining: --:--:--)
==> default: Successfully added box 'ubuntu/xenial64' (v20170922.0.0) for 'virtualbox'!
==> default: Importing base box 'ubuntu/xenial64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/xenial64' is up to date...
==> default: Setting the name of the VM: toro-net-master_default_1506291332950_9311
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 8080 (guest) => 8080 (host) (adapter 1)
    default: 3000 (guest) => 3000 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: ubuntu
    default: SSH auth method: password
    default: Warning: Connection aborted. Retrying...
    default: Warning: Connection aborted. Retrying...
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'unknown' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.

**Comment by nolanruss** [comment]
You may need to check your virtualization settings. If you are running Windows Home, you need to access the UEFI firmware settings to enable virtualization.  Otherwise, you can enable Hyper-V settings.  Try the resources below for help:
 * https://www.howtogeek.com/213795/how-to-enable-intel-vt-x-in-your-computers-bios-or-uefi-firmware/
 * https://www.youtube.com/watch?v=zIm7f5Epd9U
 * https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/quick-start/enable-hyper-v
