### ISSUE TITLE
Update requirements

### ISSUE THREAD

**Issue by john-csudh** [csudh/toro-net#4]
Team leads, please update the wiki to use native `markdown` syntax for your section of the non-function requirements.  Your section should look like the `Testing Team` portion (see below).  We will assign this to Requirements Team lead @Felixwhwang, then he'll punt it to Architecture Team lead @mattlevan, then to Testing Team lead @juancleon, then to Frontend Team lead @maefranco, then to Backend Team lead @Janani1989.  Do not edit your section until it's been assigned to you.

TODO:

- [x] Requirements Team
- [x] Architecture Team
- [x] Testing Team (add a summary section below your table)
- [x] Frontend Team
- [x] Backend Team
- [x] ~~DevOps Team~~~ 

![screen shot 2017-09-18 at 7 48 51 pm](https://user-images.githubusercontent.com/24843326/30573799-ace555e2-9caa-11e7-87e1-c5a026eed480.png)

Remember our goal is to be consistent and clean.

**Comment by Felixwhwang** [comment]
@mattlevan I am done, it's your turn.

**Comment by john-csudh** [comment]
@Felixwhwang please make sure that you QA the final page so that it's consistent across all of the tables.  See how two tables are different.

<img width="761" alt="screen shot 2017-09-21 at 1 59 09 pm" src="https://user-images.githubusercontent.com/24843326/30718638-6207c1ae-9ed5-11e7-800e-2a2c7cb710ad.png">

<img width="752" alt="screen shot 2017-09-21 at 1 59 27 pm" src="https://user-images.githubusercontent.com/24843326/30718640-621eb5f8-9ed5-11e7-8624-70ee9a4c15e7.png">

@mattlevan please update the Architecture requirements section then punt to the next person.

**Comment by maefranco** [comment]
@juancleon the architecture team is done. It's your turn now

**Comment by juancleon** [comment]
@maefranco all set! Thanks again for the heads up.

**Comment by maefranco** [comment]
@Janani1989 it's your turn!

**Comment by Janani1989** [comment]
I'm done with editing the wiki page for non-functional requirements!
