### ISSUE TITLE
To sync a forked repository in your local to keep up with the changes in the original repository

### ISSUE THREAD

**Issue by Janani1989** [csudh/toro-net#9]
Please follow the steps below to sync your forked repository:

1. Add original repository as upstream in your forked repository:

    cd your-local-path/toro-net

_For team-leads:_

                         git remote add upstream https://github.com/csudh/toro-net.git

_For team-members (if you forked from your team-lead)_:

                         git remote add upstream https://github.com/[team-lead-profile-name]/toro-net.git

2. Fetch from the original repository

                         git fetch upstream

3. Update your fork from original repo to keep up with their changes:

                         git pull upstream master

**Comment by mattlevan** [comment]
Awesome. This would be a great addition to the wiki!

**Comment by john-csudh** [comment]
@Janani1989 please add a page to the wiki `Development` and add tutorial on this.
